// components/Editor.tsx
import { useState } from "react";
const Editor = () => {
  const [content, setContent] = useState("");
  return (
    <div className="px-4 md:px-12 xl:px-64 py-12">
      <form>
        <div className="mb-4 w-full bg-gray-50 rounded-lg border border-[#d6d6d6] ">
          <div className="py-2 px-4 bg-gray-50 rounded-t-lg ">
            <textarea
              id="text"
              value={content}
              rows={15}
              onChange={(e) => setContent(e.target.value)}
              className="px-0 outline-none w-full resize-none whitespace-pre text-sm text-gray-900 bg-gray-50 border-0 focus:ring-0  "
              placeholder="Enter text here"
              spellCheck={false}
              required
            ></textarea>
          </div>
          <div className="flex justify-between items-center py-2 px-3 border-t ">
            <button
              type="submit"
              className="inline-flex  items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-[#24292F] hover:bg-[#24292F]/90  rounded-lg focus:ring-4 "
            >
              Create Paste
            </button>
          </div>
        </div>
      </form>
    </div>
  );
};
export default Editor;

// src/lib/components/Editor.svelte
<script lang="ts">
	import FileIcon from '$lib/icons/FileIcon.svelte';
	import CopyIcon from '$lib/icons/CopyIcon.svelte';
	import DownloadIcon from '$lib/icons/DownloadIcon.svelte';
	import SecurityIcon from '$lib/icons/SecurityIcon.svelte';
	import { DataStore } from '../../store/DataStore';
	let textareavalue: string;
	const updateValue = () => {
		DataStore.update((storevalue) => {
			return { ...storevalue, textareavalue: textareavalue };
		});
	};
</script>

<div class="border border-zinc-600 rounded">
	<div class="flex border-b border-zinc-600 p-2 items-center justify-between rounded-t">
		<div>
			<FileIcon size={20} color="#808080" />
		</div>
		<div class="flex items-center space-x-4">
			<div class="flex divide-x divide-zinc-600 border border-zinc-600 rounded bg-[#333238]">
				<button class="p-1 bg-transparent"><CopyIcon size={20} color="#808080" /></button>
				<button class="p-1 bg-transparent"><FileIcon size={20} color="#808080" /></button>
				<button class="p-1 bg-transparent"><DownloadIcon size={20} color="#808080" /></button>
			</div>
			<a href="#">
				<div class="border border-zinc-600 rounded p-1 bg-[#333238]">
					<SecurityIcon size={20} color="#808080" />
				</div>
			</a>
		</div>
	</div>
	<div class="p-4 bg-[#1D1F21] rounded">
		<textarea
			class="outline-none w-full resize-none whitespace-pre text-white text-sm bg-[#1D1F21] h-[50vh]"
			placeholder="Enter text here"
			spellCheck={false}
			required
			bind:value={textareavalue}
			on:change={updateValue}
		/>
	</div>
</div>
